[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.17'
remappings = [
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts',
    'operator-filter-registry/=lib/operator-filter-registry/src/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'seadrop/=src/',
    'utility-contracts/=lib/utility-contracts/src/',
    'utility-contracts/=lib/utility-contracts/src/',
]
optimizer = true
optimizer_runs = 1_000_000
via_ir = true
ignored_error_codes = []
bytecode_hash = "none"
ffi = false

[profile.upgradeable]
src = 'src-upgradeable/src/'

[profile.ir_inspect]
test = 'src'

[rpc_endpoints]
goerli = '${GOERLI_RPC_URL}'
mainnet = '${ETHEREUM_RPC_URL}'
etherscan_api_key = '${ETHERSCAN_API_KEY}'

# See more config options https://github.com/foundry-rs/foundry/blob/f95fb9b543cab101e89b9d29f9b330c1203d4e33/crates/config/README.md?plain=1#L89
